apiVersion: "sample.javaoperatorsdk/v1"
kind: WebPage
metadata:
  name: hello
spec:
  exposed: false
  html: |
    <html>
      <head>
        <title>Hello Operator World</title>
      </head>
      <body>
        Hello World! 
      </body>
    </html>